// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbyPoints.Data;

#nullable disable

namespace WebbyPoints.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529174023_SeedNewPlacesAndRewards")]
    partial class SeedNewPlacesAndRewards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WebbyPoints.Models.Canje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoVoucher")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCanje")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntosGastados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVoucher")
                        .IsUnique();

                    b.HasIndex("RecompensaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Canjes");
                });

            modelBuilder.Entity("WebbyPoints.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAsistencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoInteresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Distancia")
                        .HasColumnType("REAL");

                    b.Property<bool>("EsEventoEspecial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecioRango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntosRecompensa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuntosInteres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calificacion = 4.5,
                            Categoria = "Estudio",
                            Descripcion = "El lugar ideal para concentrarse con un buen café y WiFi estable.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Starbucks Central",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Principal 123"
                        },
                        new
                        {
                            Id = 2,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Ocio",
                            Descripcion = "Bar con ambiente relajado, perfecto para un after-class.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "04:00 PM - 02:00 AM",
                            ImagenUrl = "/images/bodega_esquina.png",
                            Nombre = "La Bodega de la Esquina",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Calle Universitaria 456"
                        },
                        new
                        {
                            Id = 3,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Romántico",
                            Descripcion = "Vista increíble y ambiente tranquilo para una cita especial.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "06:00 AM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1529619768328-e37af76c6fe5",
                            Nombre = "Mirador del Parque",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Malecón de los Estudiantes"
                        },
                        new
                        {
                            Id = 4,
                            Calificacion = 4.2000000000000002,
                            Categoria = "Estudio",
                            Descripcion = "Silencio absoluto y miles de libros a tu disposición.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "08:00 AM - 08:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1521587760476-6c12a4b040da",
                            Nombre = "Biblioteca Nacional (Sede Norte)",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Cultura 789"
                        },
                        new
                        {
                            Id = 5,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Comida",
                            Descripcion = "Las mejores pizzas artesanales para compartir.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:00 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Nombre = "Pizza & Chill",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Pasaje Gastronómico 10"
                        },
                        new
                        {
                            Id = 6,
                            Calificacion = 4.4000000000000004,
                            Categoria = "Ocio",
                            Descripcion = "Estrenos con descuento para universitarios.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "02:00 PM - 12:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                            Nombre = "Cine Planetario",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Centro Comercial El Polo"
                        },
                        new
                        {
                            Id = 7,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Únete a la jornada ecológica de limpieza en la Costa Verde. Contribuye al medio ambiente y gana puntos extra.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 01:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1618477460930-d8c0465e5744",
                            Nombre = "Limpieza de Playas - Costa Verde",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Playa Costa Verde, Miraflores"
                        },
                        new
                        {
                            Id = 8,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Cultura",
                            Descripcion = "Recorre las galerías del MALI con entrada libre para universitarios. Arte contemporáneo y clásico peruano.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "06:00 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1554907984-15263bfd63bd",
                            Nombre = "Noche de Museos - Museo de Arte de Lima",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque de la Exposición, Cercado de Lima"
                        },
                        new
                        {
                            Id = 9,
                            Calificacion = 5.0,
                            Categoria = "Cívico",
                            Descripcion = "Ayuda en la preparación y distribución de alimentos para familias vulnerables en Lima Norte.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "08:00 AM - 02:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1593113598332-cd288d649433",
                            Nombre = "Voluntariado - Comedor Popular San Martín",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Jr. San Martín 450, Los Olivos"
                        },
                        new
                        {
                            Id = 10,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Participa en la reforestación urbana plantando árboles nativos en el Parque Ecológico de Villa El Salvador.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 12:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09",
                            Nombre = "Siembra de Árboles - Parque Ecológico",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque Ecológico, Villa El Salvador"
                        },
                        new
                        {
                            Id = 11,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Cultura",
                            Descripcion = "La feria literaria más importante del país. Cientos de stands, presentaciones de libros y conversatorios culturales.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "11:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1481627834876-b7833e8f5570",
                            Nombre = "Feria Internacional del Libro de Lima",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque Próceres de la Independencia, Jesús María"
                        },
                        new
                        {
                            Id = 12,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Comida",
                            Descripcion = "Experiencia culinaria inigualable a cargo del chef Virgilio Martínez. Platos basados en insumos de diversas alturas geográficas.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:45 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1544025162-d76694265947",
                            Nombre = "Central Restaurante",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Pedro de Osma 301, Barranco"
                        },
                        new
                        {
                            Id = 13,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Comida",
                            Descripcion = "Los mejores sándwiches criollos tradicionales con papas nativas fritas y jugos naturales. Un sabor inconfundible.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:00 AM - 01:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1509722747041-616f39b57569",
                            Nombre = "La Lucha Sanguchería Criolla",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Pasaje Champagnat 139, Miraflores"
                        },
                        new
                        {
                            Id = 14,
                            Calificacion = 4.5,
                            Categoria = "Ocio",
                            Descripcion = "Histórico bar limeño, reconocido como el lugar donde se perfeccionó la receta original del emblemático Pisco Sour.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:00 PM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b",
                            Nombre = "Bar Maury (Centro de Lima)",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Jr. Carabaya 387, Centro de Lima"
                        },
                        new
                        {
                            Id = 15,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Cultural",
                            Descripcion = "El gran evento de cultura pop asiática en Lima. Concursos de cosplay, bandas en vivo, venta de merchandising y videojuegos.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "10:00 AM - 09:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1578632767115-351597cf2477",
                            Nombre = "Festival de Anime & Cosplay - Otaku Fest",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Centro de Convenciones de Lima, San Borja"
                        },
                        new
                        {
                            Id = 16,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Ayuda en el cuidado, alimentación y paseo de perros y gatos rescatados del abandono en este hermoso refugio animal.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "09:00 AM - 04:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e",
                            Nombre = "Voluntariado - Albergue 'Patitas Felices'",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Calle Las Flores 450, Chorrillos"
                        },
                        new
                        {
                            Id = 17,
                            Calificacion = 5.0,
                            Categoria = "Cívico",
                            Descripcion = "Comparte una tarde de juegos, lectura y conversación con personas de la tercera edad que necesitan compañía y afecto.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "02:00 PM - 06:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289",
                            Nombre = "Apoyo al Adulto Mayor - Asilo Canevaro",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Jr. Áncash 1400, Barrios Altos, Centro de Lima"
                        },
                        new
                        {
                            Id = 18,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Comida",
                            Descripcion = "Alta cocina peruana de autor en una hermosa casona histórica de San Isidro. Platos criollos reinterpretados de manera gourmet.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:00 PM - 11:30 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
                            Nombre = "Astrid & Gastón",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Paz Soldán 290, San Isidro"
                        },
                        new
                        {
                            Id = 19,
                            Calificacion = 4.4000000000000004,
                            Categoria = "Estudio",
                            Descripcion = "Discusión mensual de obras contemporáneas peruanas y latinoamericanas en un ambiente ameno y rodeado de libros.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "04:00 PM - 07:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1529156069898-49953e39b3ac",
                            Nombre = "Club de Lectura - Biblioteca Municipal",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Larco 770, Miraflores"
                        },
                        new
                        {
                            Id = 20,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Ocio",
                            Descripcion = "Ven a jugar Catán, Dixit o Carcassonne con amigos o conoce gente nueva compartiendo juegos modernos de mesa.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "02:00 PM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09",
                            Nombre = "Tarde de Juegos de Mesa - Portal de Ocio",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Calle Cantuarias 140, Miraflores"
                        },
                        new
                        {
                            Id = 21,
                            Calificacion = 4.5,
                            Categoria = "Ocio",
                            Descripcion = "Box privados para cantar a todo pulmón con una enorme selección de canciones y excelente servicio de coctelería y snacks.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "06:00 PM - 03:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1516280440614-37939bbacd6a",
                            Nombre = "Karaoke Sopranos Surco",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Primavera 1540, Santiago de Surco"
                        },
                        new
                        {
                            Id = 22,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Comida",
                            Descripcion = "Platos de antaño servidos en generosas porciones ideales para compartir en familia o con esa persona especial. El sabor de casa.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:00 PM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
                            Nombre = "Isolina Taberna Peruana",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. San Martín 101, Barranco"
                        },
                        new
                        {
                            Id = 23,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Deporte",
                            Descripcion = "El domingo por la mañana la Av. Arequipa se cierra al tráfico motorizado y se abre completamente para bicicletas, patines y caminatas.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 01:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1541614101331-1a5a3a194e92",
                            Nombre = "CicloDía - Av. Arequipa Libre",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Av. Arequipa (Cdra 1 a 52), Lima"
                        },
                        new
                        {
                            Id = 24,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Deporte",
                            Descripcion = "Únete a grupos de corredores para recorrer el perímetro verde de la comandancia militar. Excelente ruta iluminada y segura.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "05:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8",
                            Nombre = "Running Club - El Pentagonito",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. San Borja Sur, San Borja"
                        },
                        new
                        {
                            Id = 25,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Deporte",
                            Descripcion = "Aprende a domar las olas con profesores calificados en la Costa Verde. Incluye tabla de surf y traje de neopreno.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "06:00 AM - 05:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1502680390469-be75c86b636f",
                            Nombre = "Clases de Surf en Playa Makaha",
                            PlanTipo = "Solo",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Playa Makaha, Miraflores"
                        },
                        new
                        {
                            Id = 26,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Romántico",
                            Descripcion = "Parque de fuentes ornamentales con espectáculos multimedia interactivos de agua, luces y música. Un paseo romántico perfecto.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "03:00 PM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1504214208698-ea1916a2195a",
                            Nombre = "Circuito Mágico del Agua",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Jr. Madre de Dios S/N, Cercado de Lima"
                        },
                        new
                        {
                            Id = 27,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Romántico",
                            Descripcion = "Vista hermosa de la bahía de Lima, murales de mosaicos coloridos y la icónica escultura de 'El Beso' de Víctor Delfín.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "24 Horas",
                            ImagenUrl = "https://images.unsplash.com/photo-1518199266791-5375a83190b7",
                            Nombre = "El Parque del Amor",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Malecón Cisneros, Miraflores"
                        },
                        new
                        {
                            Id = 28,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Estudio",
                            Descripcion = "Una hermosa y pequeña cafetería-librería en Barranco donde puedes leer en silencio mientras disfrutas de un té artesanal.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "09:00 AM - 09:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
                            Nombre = "Café Cultural La Libre",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. San Martín 108, Barranco"
                        },
                        new
                        {
                            Id = 29,
                            Calificacion = 4.5,
                            Categoria = "Estudio",
                            Descripcion = "Estudio académico con amplias salas de lectura silenciosa, computadoras de consulta y bibliotecología especializada.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "08:00 AM - 09:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1521587760476-6c12a4b040da",
                            Nombre = "Biblioteca de la USMP (Sede La Molina)",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Los Corregidores 1150, La Molina"
                        },
                        new
                        {
                            Id = 30,
                            Calificacion = 4.2999999999999998,
                            Categoria = "Estudio",
                            Descripcion = "Ubicación estratégica frente al campus universitario para hacer trabajos grupales, estudiar para parciales o tomar un espresso.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Starbucks USMP (Sede Santa Anita)",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Los Calamacos 450, Santa Anita"
                        },
                        new
                        {
                            Id = 31,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Comida",
                            Descripcion = "Feria gastronómica dentro del campus universitario. Expositores de comida selvática, marina y andina a precios de estudiante.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "10:00 AM - 06:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
                            Nombre = "Festival Mistura USMP (Feria Gastronómica)",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque de la Exposición, Lima"
                        },
                        new
                        {
                            Id = 32,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Cultura",
                            Descripcion = "Espectacular casona virreinal que alberga una de las colecciones precolombinas de oro y plata más impresionantes del mundo.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "09:00 AM - 07:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1566121318599-8cf0c7921a8f",
                            Nombre = "Museo Larco",
                            PlanTipo = "Solo",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Simón Bolívar 1515, Pueblo Libre"
                        },
                        new
                        {
                            Id = 33,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Cultura",
                            Descripcion = "Disfruta de las mejores temporadas de ópera, ballet y conciertos de la Orquesta Sinfónica Nacional con acústica de primer nivel mundial.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:30 PM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1503095396549-807759245b35",
                            Nombre = "Gran Teatro Nacional (Sinfónica)",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Javier Prado Este 2225, San Borja"
                        },
                        new
                        {
                            Id = 34,
                            Calificacion = 5.0,
                            Categoria = "Cívico",
                            Descripcion = "Sé un héroe cívico donando sangre para el banco nacional. Un acto altruista que salva hasta tres vidas humanas.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 02:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1615461066841-6116e61058f4",
                            Nombre = "Donación de Sangre - Hospital Rebagliati",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Av. Edgardo Rebagliati 490, Jesús María"
                        },
                        new
                        {
                            Id = 35,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Sube las hermosas lomas costeras durante el invierno limeño para plantar semillas de flora nativa y proteger el ecosistema de la neblina.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 01:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
                            Nombre = "Reforestación - Lomas de Villa María",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Lomas de Villa Maria del Triunfo, VMT"
                        },
                        new
                        {
                            Id = 36,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Jornada cívica y ecológica para recolectar desechos plásticos en una de las playas más contaminadas del litoral del Callao.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "08:00 AM - 02:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1618477460930-d8c0465e5744",
                            Nombre = "Limpieza Extrema - Playa Carpayo",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Playa Carpayo, Chucuito, Callao"
                        },
                        new
                        {
                            Id = 37,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Ocio",
                            Descripcion = "Impresionante bar de tragos de autor ubicado en una mansión restaurada del siglo XIX. Hermosa decoración barroca criolla.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "06:00 PM - 02:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1470337458703-46ad1756a187",
                            Nombre = "Bar Ayahuasca Barranco",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Prolongación San Martin 130, Barranco"
                        },
                        new
                        {
                            Id = 38,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Romántico",
                            Descripcion = "Disfruta de una cena espectacular a la luz de las velas frente al impresionante centro ceremonial precolombino iluminado.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:00 PM - 11:30 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
                            Nombre = "Huaca Pucllana (Cena Temática)",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/S/S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Calle General Borgoño 8ra cdra, Miraflores"
                        },
                        new
                        {
                            Id = 39,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Ocio",
                            Descripcion = "La convención de cultura pop geek más grande de Lima. Stands de Marvel, DC, ilustradores, actores internacionales invitados y cosplay.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "11:00 AM - 09:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f",
                            Nombre = "Comic Con Lima",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Centro de Exposiciones Jockey, Surco"
                        },
                        new
                        {
                            Id = 40,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Cultura",
                            Descripcion = "Histórica y espaciosa librería limeña, ideal para tomar un café mientras ojeas las últimas novedades editoriales nacionales.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "09:30 AM - 09:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794",
                            Nombre = "Librería El Virrey Miraflores",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Calle Bolognesi 510, Miraflores"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CostoPuntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recompensas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Categoria = "Descuento",
                            CostoPuntos = 50,
                            Descripcion = "Un café de cualquier tamaño en el Starbucks frente a la sede de Santa Anita. Válido por 7 días.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(427),
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Café Gratis en Starbucks USMP",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Categoria = "Descuento",
                            CostoPuntos = 80,
                            Descripcion = "Descuento del 15% en tu cuenta total. Presentar voucher al mesero. Válido por 14 días.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2381),
                            ImagenUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Nombre = "15% de Descuento en Pizza & Chill",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Categoria = "Ocio",
                            CostoPuntos = 150,
                            Descripcion = "Dos entradas para cualquier función de lunes a jueves. Válido por 30 días.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2387),
                            ImagenUrl = "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                            Nombre = "Entrada Doble al Cine Planetario",
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Categoria = "Merchandising",
                            CostoPuntos = 200,
                            Descripcion = "Termo de acero inoxidable de 500ml con el logo de la USMP. Edición limitada.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2388),
                            ImagenUrl = "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
                            Nombre = "Termo Coleccionable USMP",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Categoria = "Experiencia",
                            CostoPuntos = 120,
                            Descripcion = "Entrada gratuita al Circuito Mágico del Agua para ti y un acompañante. Válido fines de semana.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2389),
                            ImagenUrl = "https://images.unsplash.com/photo-1504214208698-ea1916a2195a",
                            Nombre = "Pase Libre - Parque de las Aguas",
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Categoria = "Merchandising",
                            CostoPuntos = 300,
                            Descripcion = "Polera de algodón premium con el diseño exclusivo de WebbyPoints. Tallas S, M, L, XL.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2390),
                            ImagenUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
                            Nombre = "Polera Oficial WebbyPoints",
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Categoria = "Experiencia",
                            CostoPuntos = 400,
                            Descripcion = "Recorrido guiado por 4 restaurantes emblemáticos de Barranco con degustación incluida.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2391),
                            ImagenUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
                            Nombre = "Tour Gastronómico por Barranco",
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Categoria = "Cultura",
                            CostoPuntos = 180,
                            Descripcion = "Acceso VIP al Museo de Arte de Lima con guía personalizado para ti y 2 amigos.",
                            FechaCreacion = new DateTime(2026, 5, 29, 12, 40, 22, 993, DateTimeKind.Local).AddTicks(2392),
                            ImagenUrl = "https://images.unsplash.com/photo-1554907984-15263bfd63bd",
                            Nombre = "Entrada al Museo MALI + Guía",
                            Stock = 25
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calificacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoInteresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Carrera = "Ingenieria de Sistemas",
                            Edad = 21,
                            Email = "cesar_paredes7@usmp.pe",
                            EsAdmin = true,
                            FechaRegistro = new DateTime(2026, 5, 29, 12, 40, 22, 990, DateTimeKind.Local).AddTicks(2303),
                            Nombre = "César Paredes",
                            Password = "Vinicola14//",
                            Preferencias = "Estudio, Ocio, Comida, Cultura",
                            Puntos = 2000,
                            Rango = "Administrador",
                            Universidad = "USMP"
                        },
                        new
                        {
                            Id = 200,
                            Carrera = "Ingenieria de Sistemas",
                            Edad = 21,
                            Email = "fausto_miranda@usmp.pe",
                            EsAdmin = true,
                            FechaRegistro = new DateTime(2026, 5, 29, 12, 40, 22, 991, DateTimeKind.Local).AddTicks(9495),
                            Nombre = "Fausto Miranda",
                            Password = "Mimamamemima123",
                            Preferencias = "Estudio, Ocio, Comida, Cultura",
                            Puntos = 1000,
                            Rango = "Administrador",
                            Universidad = "USMP"
                        },
                        new
                        {
                            Id = 300,
                            Carrera = "Medicina",
                            Edad = 20,
                            Email = "juan_perez@usmp.pe",
                            EsAdmin = false,
                            FechaRegistro = new DateTime(2026, 5, 29, 12, 40, 22, 991, DateTimeKind.Local).AddTicks(9511),
                            Nombre = "Juan Pérez",
                            Password = "Juanito123//",
                            Preferencias = "Comida, Parques",
                            Puntos = 500,
                            Rango = "Explorador",
                            Universidad = "USMP"
                        },
                        new
                        {
                            Id = 301,
                            Carrera = "Derecho",
                            Edad = 22,
                            Email = "maria_rojas@usmp.pe",
                            EsAdmin = false,
                            FechaRegistro = new DateTime(2026, 5, 29, 12, 40, 22, 991, DateTimeKind.Local).AddTicks(9513),
                            Nombre = "María Rojas",
                            Password = "Maria1234//",
                            Preferencias = "Cafés, Estudiar",
                            Puntos = 500,
                            Rango = "Explorador",
                            Universidad = "USMP"
                        },
                        new
                        {
                            Id = 302,
                            Carrera = "Psicologia",
                            Edad = 19,
                            Email = "luis_flores@usmp.pe",
                            EsAdmin = false,
                            FechaRegistro = new DateTime(2026, 5, 29, 12, 40, 22, 991, DateTimeKind.Local).AddTicks(9514),
                            Nombre = "Luis Flores",
                            Password = "Luisito99//",
                            Preferencias = "Gaming, Bares",
                            Puntos = 500,
                            Rango = "Explorador",
                            Universidad = "USMP"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Canje", b =>
                {
                    b.HasOne("WebbyPoints.Models.Recompensa", "Recompensa")
                        .WithMany("Canjes")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("Canjes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.CheckIn", b =>
                {
                    b.HasOne("WebbyPoints.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("CheckIns")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("CheckIns")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.HasOne("WebbyPoints.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("Reseñas")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("Reseñas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Recompensa", b =>
                {
                    b.Navigation("Canjes");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Navigation("Canjes");

                    b.Navigation("CheckIns");

                    b.Navigation("Reseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
