// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbyPoints.Data;

#nullable disable

namespace WebbyPoints.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529034501_AddCheckInTable")]
    partial class AddCheckInTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WebbyPoints.Models.Canje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoVoucher")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCanje")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntosGastados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVoucher")
                        .IsUnique();

                    b.HasIndex("RecompensaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Canjes");
                });

            modelBuilder.Entity("WebbyPoints.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAsistencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoInteresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Distancia")
                        .HasColumnType("REAL");

                    b.Property<bool>("EsEventoEspecial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecioRango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntosRecompensa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuntosInteres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calificacion = 4.5,
                            Categoria = "Estudio",
                            Descripcion = "El lugar ideal para concentrarse con un buen café y WiFi estable.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "07:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Starbucks Central",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Principal 123"
                        },
                        new
                        {
                            Id = 2,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Ocio",
                            Descripcion = "Bar con ambiente relajado, perfecto para un after-class.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "04:00 PM - 02:00 AM",
                            ImagenUrl = "/images/bodega_esquina.png",
                            Nombre = "La Bodega de la Esquina",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Calle Universitaria 456"
                        },
                        new
                        {
                            Id = 3,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Romántico",
                            Descripcion = "Vista increíble y ambiente tranquilo para una cita especial.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "06:00 AM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1529619768328-e37af76c6fe5",
                            Nombre = "Mirador del Parque",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Malecón de los Estudiantes"
                        },
                        new
                        {
                            Id = 4,
                            Calificacion = 4.2000000000000002,
                            Categoria = "Estudio",
                            Descripcion = "Silencio absoluto y miles de libros a tu disposición.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "08:00 AM - 08:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1521587760476-6c12a4b040da",
                            Nombre = "Biblioteca Nacional (Sede Norte)",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Av. Cultura 789"
                        },
                        new
                        {
                            Id = 5,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Comida",
                            Descripcion = "Las mejores pizzas artesanales para compartir.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "12:00 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Nombre = "Pizza & Chill",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Pasaje Gastronómico 10"
                        },
                        new
                        {
                            Id = 6,
                            Calificacion = 4.4000000000000004,
                            Categoria = "Ocio",
                            Descripcion = "Estrenos con descuento para universitarios.",
                            Distancia = 0.0,
                            EsEventoEspecial = false,
                            Etiquetas = "",
                            Horario = "02:00 PM - 12:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                            Nombre = "Cine Planetario",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 10,
                            Ubicacion = "Centro Comercial El Polo"
                        },
                        new
                        {
                            Id = 7,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Únete a la jornada ecológica de limpieza en la Costa Verde. Contribuye al medio ambiente y gana puntos extra.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 01:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1618477460930-d8c0465e5744",
                            Nombre = "Limpieza de Playas - Costa Verde",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Playa Costa Verde, Miraflores"
                        },
                        new
                        {
                            Id = 8,
                            Calificacion = 4.7000000000000002,
                            Categoria = "Cultura",
                            Descripcion = "Recorre las galerías del MALI con entrada libre para universitarios. Arte contemporáneo y clásico peruano.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "06:00 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1554907984-15263bfd63bd",
                            Nombre = "Noche de Museos - Museo de Arte de Lima",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque de la Exposición, Cercado de Lima"
                        },
                        new
                        {
                            Id = 9,
                            Calificacion = 5.0,
                            Categoria = "Cívico",
                            Descripcion = "Ayuda en la preparación y distribución de alimentos para familias vulnerables en Lima Norte.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "08:00 AM - 02:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1593113598332-cd288d649433",
                            Nombre = "Voluntariado - Comedor Popular San Martín",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Jr. San Martín 450, Los Olivos"
                        },
                        new
                        {
                            Id = 10,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Medio Ambiente",
                            Descripcion = "Participa en la reforestación urbana plantando árboles nativos en el Parque Ecológico de Villa El Salvador.",
                            Distancia = 0.0,
                            EsEventoEspecial = true,
                            Etiquetas = "",
                            Horario = "07:00 AM - 12:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09",
                            Nombre = "Siembra de Árboles - Parque Ecológico",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            PuntosRecompensa = 25,
                            Ubicacion = "Parque Ecológico, Villa El Salvador"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CostoPuntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recompensas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Categoria = "Descuento",
                            CostoPuntos = 50,
                            Descripcion = "Un café de cualquier tamaño en el Starbucks frente a la sede de Santa Anita. Válido por 7 días.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(2870),
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Café Gratis en Starbucks USMP",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Categoria = "Descuento",
                            CostoPuntos = 80,
                            Descripcion = "Descuento del 15% en tu cuenta total. Presentar voucher al mesero. Válido por 14 días.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4215),
                            ImagenUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Nombre = "15% de Descuento en Pizza & Chill",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Categoria = "Ocio",
                            CostoPuntos = 150,
                            Descripcion = "Dos entradas para cualquier función de lunes a jueves. Válido por 30 días.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4218),
                            ImagenUrl = "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                            Nombre = "Entrada Doble al Cine Planetario",
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Categoria = "Merchandising",
                            CostoPuntos = 200,
                            Descripcion = "Termo de acero inoxidable de 500ml con el logo de la USMP. Edición limitada.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4220),
                            ImagenUrl = "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
                            Nombre = "Termo Coleccionable USMP",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Categoria = "Experiencia",
                            CostoPuntos = 120,
                            Descripcion = "Entrada gratuita al Circuito Mágico del Agua para ti y un acompañante. Válido fines de semana.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4221),
                            ImagenUrl = "https://images.unsplash.com/photo-1504214208698-ea1916a2195a",
                            Nombre = "Pase Libre - Parque de las Aguas",
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Categoria = "Merchandising",
                            CostoPuntos = 300,
                            Descripcion = "Polera de algodón premium con el diseño exclusivo de WebbyPoints. Tallas S, M, L, XL.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4222),
                            ImagenUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
                            Nombre = "Polera Oficial WebbyPoints",
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Categoria = "Experiencia",
                            CostoPuntos = 400,
                            Descripcion = "Recorrido guiado por 4 restaurantes emblemáticos de Barranco con degustación incluida.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4223),
                            ImagenUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
                            Nombre = "Tour Gastronómico por Barranco",
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Categoria = "Cultura",
                            CostoPuntos = 180,
                            Descripcion = "Acceso VIP al Museo de Arte de Lima con guía personalizado para ti y 2 amigos.",
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 45, 1, 49, DateTimeKind.Local).AddTicks(4224),
                            ImagenUrl = "https://images.unsplash.com/photo-1554907984-15263bfd63bd",
                            Nombre = "Entrada al Museo MALI + Guía",
                            Stock = 25
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calificacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoInteresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Carrera = "Ingeniería de Computación y Sistemas",
                            Edad = 21,
                            Email = "cesar_paredes7@usmp.pe",
                            EsAdmin = true,
                            FechaRegistro = new DateTime(2026, 5, 28, 22, 45, 1, 46, DateTimeKind.Local).AddTicks(6606),
                            Nombre = "César Paredes",
                            Password = "Vinicola14//",
                            Preferencias = "Todo",
                            Puntos = 999,
                            Rango = "Administrador",
                            Universidad = "USMP"
                        },
                        new
                        {
                            Id = 200,
                            Carrera = "Ingeniería de Computación y Sistemas",
                            Edad = 21,
                            Email = "fausto_miranda@usmp.pe",
                            EsAdmin = true,
                            FechaRegistro = new DateTime(2026, 5, 28, 22, 45, 1, 48, DateTimeKind.Local).AddTicks(4491),
                            Nombre = "Fausto Miranda",
                            Password = "Mimamamemima123",
                            Preferencias = "Todo",
                            Puntos = 999,
                            Rango = "Administrador",
                            Universidad = "USMP"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Canje", b =>
                {
                    b.HasOne("WebbyPoints.Models.Recompensa", "Recompensa")
                        .WithMany("Canjes")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("Canjes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.CheckIn", b =>
                {
                    b.HasOne("WebbyPoints.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("CheckIns")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("CheckIns")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.HasOne("WebbyPoints.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("Reseñas")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("Reseñas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Recompensa", b =>
                {
                    b.Navigation("Canjes");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Navigation("Canjes");

                    b.Navigation("CheckIns");

                    b.Navigation("Reseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
