// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbyPoints.Data;

#nullable disable

namespace WebbyPoints.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425061933_ActualizarImagenBodega")]
    partial class ActualizarImagenBodega
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Distancia")
                        .HasColumnType("REAL");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecioRango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuntosInteres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calificacion = 4.5,
                            Categoria = "Estudio",
                            Descripcion = "El lugar ideal para concentrarse con un buen café y WiFi estable.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "07:00 AM - 10:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
                            Nombre = "Starbucks Central",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            Ubicacion = "Av. Principal 123"
                        },
                        new
                        {
                            Id = 2,
                            Calificacion = 4.7999999999999998,
                            Categoria = "Ocio",
                            Descripcion = "Bar con ambiente relajado, perfecto para un after-class.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "04:00 PM - 02:00 AM",
                            ImagenUrl = "/images/bodega_esquina.png",
                            Nombre = "La Bodega de la Esquina",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            Ubicacion = "Calle Universitaria 456"
                        },
                        new
                        {
                            Id = 3,
                            Calificacion = 4.9000000000000004,
                            Categoria = "Romántico",
                            Descripcion = "Vista increíble y ambiente tranquilo para una cita especial.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "06:00 AM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1529619768328-e37af76c6fe5",
                            Nombre = "Mirador del Parque",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            Ubicacion = "Malecón de los Estudiantes"
                        },
                        new
                        {
                            Id = 4,
                            Calificacion = 4.2000000000000002,
                            Categoria = "Estudio",
                            Descripcion = "Silencio absoluto y miles de libros a tu disposición.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "08:00 AM - 08:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1521587760476-6c12a4b040da",
                            Nombre = "Biblioteca Nacional (Sede Norte)",
                            PlanTipo = "Solo",
                            PrecioRango = "S/",
                            Ubicacion = "Av. Cultura 789"
                        },
                        new
                        {
                            Id = 5,
                            Calificacion = 4.5999999999999996,
                            Categoria = "Comida",
                            Descripcion = "Las mejores pizzas artesanales para compartir.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "12:00 PM - 11:00 PM",
                            ImagenUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Nombre = "Pizza & Chill",
                            PlanTipo = "Amigos",
                            PrecioRango = "S/",
                            Ubicacion = "Pasaje Gastronómico 10"
                        },
                        new
                        {
                            Id = 6,
                            Calificacion = 4.4000000000000004,
                            Categoria = "Ocio",
                            Descripcion = "Estrenos con descuento para universitarios.",
                            Distancia = 0.0,
                            Etiquetas = "",
                            Horario = "02:00 PM - 12:00 AM",
                            ImagenUrl = "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                            Nombre = "Cine Planetario",
                            PlanTipo = "Pareja",
                            PrecioRango = "S/",
                            Ubicacion = "Centro Comercial El Polo"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calificacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoInteresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Carrera = "Ingeniería de Computación y Sistemas",
                            Edad = 21,
                            Email = "cesar_paredes7@usmp.pe",
                            EsAdmin = true,
                            FechaRegistro = new DateTime(2026, 4, 25, 1, 19, 32, 261, DateTimeKind.Local).AddTicks(7303),
                            Nombre = "César Paredes",
                            Password = "Vinicola14//",
                            Preferencias = "Todo",
                            Puntos = 999,
                            Rango = "Administrador",
                            Universidad = "USMP"
                        });
                });

            modelBuilder.Entity("WebbyPoints.Models.Reseña", b =>
                {
                    b.HasOne("WebbyPoints.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("Reseñas")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbyPoints.Models.Usuario", "Usuario")
                        .WithMany("Reseñas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebbyPoints.Models.PuntoInteres", b =>
                {
                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("WebbyPoints.Models.Usuario", b =>
                {
                    b.Navigation("Reseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
